# 100 exercícios - numpy

Esta é uma coleção de exercícios que foram reunidos na lista de discussão do NumPy, no Stack Overflow e na documentação do NumPy. O objetivo desta coleção é oferecer uma referência rápida tanto para usuários antigos quanto para novos, além de fornecer um conjunto de exercícios para professores.

Se você encontrar algum erro ou achar que tem uma maneira melhor de resolver algum deles, sinta-se à vontade para abrir uma issue em <https://github.com/rougier/numpy-100>.

* Arquivo gerado automaticamente. Consulte a documentação para atualizar perguntas/respostas/dicas programaticamente.


#### 1. Importe o pacote numpy com o nome `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Imprima a versão do NumPy e a configuração (★☆☆)

In [ ]:
print(np.__version__)
print('\n')
np.show_config()

#### 3. Crie um vetor nulo de tamanho 10 (★☆☆)

In [9]:
vetor_nulo = np.zeros(10)
print(vetor_nulo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Como encontrar o tamanho da memória de qualquer array (★☆☆)

In [52]:
array_qualquer = np.array([1, 2, 3, 4])

print('Usando .nbytes:', array_qualquer.nbytes)
print('Usando .size * .itemsize:', array_qualquer.size * array_qualquer.itemsize)


Usando .nbytes: 32
Usando .size * .itemsize: 32


#### 5. Como obter a documentação da função `numpy add` a partir da linha de comando? (★☆☆)

In [54]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Crie um vetor nulo de tamanho 10, mas com o quinto valor igual a 1 (★☆☆)

In [20]:
nulo_10 = np.zeros(10)

nulo_10[4] = 1

print(nulo_10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Crie um vetor com valores que variam de 10 a 49 (★☆☆)

In [55]:
vetor_aleatorio = np.linspace(10, 50, 10, dtype=int)
print(vetor_aleatorio)

[10 14 18 23 27 32 36 41 45 50]


#### 8. Inverter um vetor (o primeiro elemento torna-se o último) (★☆☆)

In [ ]:
vetor_invertido = np.flip(vetor_aleatorio)

print(vetor_aleatorio, '\n')
print(vetor_invertido)
print(vetor_aleatorio[::-1])

[10 14 18 23 27 32 36 41 45 50]


[50 45 41 36 32 27 23 18 14 10]
[50 45 41 36 32 27 23 18 14 10]


#### 9. Crie uma matriz 3x3 com valores variando de 0 a 8 (★☆☆)

In [ ]:
matriz_3_3 = np.arange(9).reshape(3, 3)

print(matriz_3_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Encontre os índices dos elementos não nulos em [1,2,0,0,4,0] (★☆☆)

In [57]:
q10 = [1,2,0,0,4,0]

print(q10, '\n')
print(np.nonzero(q10))

[1, 2, 0, 0, 4, 0] 

(array([0, 1, 4]),)


#### 11. Crie uma matriz identidade 3x3 (★☆☆)

In [59]:
identidade = np.identity(3)

print(identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Crie um array 3x3x3 com valores aleatórios (★☆☆)

In [ ]:
matriz_3d_aleatoria = np.random.randn(3,3,3) # valores aleatórios da distribuição normal.

print(matriz_3d_aleatoria)

[[[-1.17019819 -0.39187662 -0.49641772]
  [ 1.22307395  0.03445608  0.27793867]
  [ 0.91473891 -1.00503442 -1.7747555 ]]

 [[ 0.74725256 -2.42709308 -0.31824606]
  [ 0.06031084 -1.13844966  1.06969295]
  [-1.03612008 -1.0143991  -0.23823782]]

 [[-1.01720434  2.08687369  1.40816746]
  [-0.41319374  0.81452178  0.20011362]
  [ 0.58085261 -0.08852252  0.94756215]]]


#### 13. Crie um array 10x10 com valores aleatórios e encontre os valores mínimo e máximo (★☆☆)

In [ ]:
matriz_10_10 = np.random.randint(10, 10000, (10, 10)) # Valores aleatórios entre 10 e 10000

print(matriz_10_10, '\n')
print('Mínimo:', matriz_10_10.min())
print('Máximo:', matriz_10_10.max())

[[2200  575 4142 7080 4648 6358 5306 5249 1298 1913]
 [5882 6415 3340 9294 3657 2330 7964 8242 1477 1752]
 [3428 1586 9601 2962 2748 1653 2033 5699 8237 1969]
 [8420 8857  488 4823 5866 6751 3181 7482 6551 4115]
 [9119 5028 8147 8239 8242 8367 6338 4143 2732 3937]
 [8587  354 8753 9375 6150 6077 8331 1899 6131 7275]
 [8021  773 3515 6793 7970 9623 5807 1641  720 8271]
 [5154 1922 3912 5573 7591 7057 2988 8127 4465 2238]
 [9385 5546 9924 8994 2361 2718 2445 7583 2251  679]
 [6368 2016 2063 8603 8879 1933 2239 6758 9572 3378]] 

Mínimo: 354
Máximo: 9924


#### 14. Crie um vetor aleatório de tamanho 30 e encontre o valor médio (★☆☆)

In [ ]:
vetor_aleatorio_30 = np.random.randint(1, 1000, 30) # Valores aleatórios entre 1 e 1000

print(vetor_aleatorio_30, '\n')

print('Média:', vetor_aleatorio_30.mean())

[ 49 258 937 318 892 522 330 533 137 754 125 102 352 500 843 981 333 779
  36 928 630 660 111 943  16 649 800 735 570 584] 

Média: 513.5666666666667


#### 15. Crie uma matriz 2D com 1 na borda e 0 no interior (★☆☆)

In [49]:
def borda_1(linhas, colunas):
    matriz = np.ones((linhas, colunas), dtype=int)
    matriz[1:-1,1:-1] = 0
    return matriz

print(borda_1(4,6),'\n')
print(borda_1(3,3),'\n')
print(borda_1(7,10))

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]] 

[[1 1 1]
 [1 0 1]
 [1 1 1]] 

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


#### 16. Como adicionar uma borda (preenchida com zeros) em torno de um array existente? (★☆☆)

In [ ]:
print(matriz_10_10, '\n')

def borda_0(matriz_ref, c_v=0):
    Z = np.pad(matriz_ref, pad_width=1, mode='constant', constant_values=c_v)
    return Z

print(borda_0(matriz_10_10))

[[2200  575 4142 7080 4648 6358 5306 5249 1298 1913]
 [5882 6415 3340 9294 3657 2330 7964 8242 1477 1752]
 [3428 1586 9601 2962 2748 1653 2033 5699 8237 1969]
 [8420 8857  488 4823 5866 6751 3181 7482 6551 4115]
 [9119 5028 8147 8239 8242 8367 6338 4143 2732 3937]
 [8587  354 8753 9375 6150 6077 8331 1899 6131 7275]
 [8021  773 3515 6793 7970 9623 5807 1641  720 8271]
 [5154 1922 3912 5573 7591 7057 2988 8127 4465 2238]
 [9385 5546 9924 8994 2361 2718 2445 7583 2251  679]
 [6368 2016 2063 8603 8879 1933 2239 6758 9572 3378]] 

[[   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0 2200  575 4142 7080 4648 6358 5306 5249 1298 1913    0]
 [   0 5882 6415 3340 9294 3657 2330 7964 8242 1477 1752    0]
 [   0 3428 1586 9601 2962 2748 1653 2033 5699 8237 1969    0]
 [   0 8420 8857  488 4823 5866 6751 3181 7482 6551 4115    0]
 [   0 9119 5028 8147 8239 8242 8367 6338 4143 2732 3937    0]
 [   0 8587  354 8753 9375 6150 6077 8331 1899 6131 7275    0]
 [   0 8021  773 3515 6793

#### 17. Qual é o resultado da seguinte expressão? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [69]:
print('0 * np.nan:', 'nan')
print('np.nan == np.nan:', 'False')
print('np.inf > np.nan:', 'False')
print('np.nan - np.nan:', 'nan')
print('np.nan in set([np.nan]):', 'True')
print('0.3 == 3 * 0.1:', 'False')

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


#### 18. Crie uma matriz 5x5 com os valores 1, 2, 3 e 4 logo abaixo da diagonal (★☆☆)

In [72]:
triangulo_inf = np.diag(1+np.arange(4),k=-1)

print(triangulo_inf)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Crie um array 8x8 e preencha-a com um padrão de tabuleiro de xadrez (★☆☆)

In [83]:
xadrez = np.ones((8,8), dtype=int)
xadrez[::2, 1::2] = 0
xadrez[1::2,::2] = 0

print(xadrez)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Considere um array de formato (6,7,8), qual é o índice (x,y,z) do 100º elemento? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)