# 100 exercícios - numpy

Esta é uma coleção de exercícios que foram reunidos na lista de discussão do NumPy, no Stack Overflow e na documentação do NumPy. O objetivo desta coleção é oferecer uma referência rápida tanto para usuários antigos quanto para novos, além de fornecer um conjunto de exercícios para professores.

Se você encontrar algum erro ou achar que tem uma maneira melhor de resolver algum deles, sinta-se à vontade para abrir uma issue em <https://github.com/rougier/numpy-100>.

* Arquivo gerado automaticamente. Consulte a documentação para atualizar perguntas/respostas/dicas programaticamente.


#### 1. Importe o pacote numpy com o nome `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Imprima a versão do NumPy e a configuração (★☆☆)

In [ ]:
print(np.__version__)
print('\n')
np.show_config()

#### 3. Crie um vetor nulo de tamanho 10 (★☆☆)

In [9]:
vetor_nulo = np.zeros(10)
print(vetor_nulo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Como encontrar o tamanho da memória de qualquer array (★☆☆)

In [52]:
array_qualquer = np.array([1, 2, 3, 4])

print('Usando .nbytes:', array_qualquer.nbytes)
print('Usando .size * .itemsize:', array_qualquer.size * array_qualquer.itemsize)


Usando .nbytes: 32
Usando .size * .itemsize: 32


#### 5. Como obter a documentação da função `numpy add` a partir da linha de comando? (★☆☆)

In [54]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Crie um vetor nulo de tamanho 10, mas com o quinto valor igual a 1 (★☆☆)

In [20]:
nulo_10 = np.zeros(10)

nulo_10[4] = 1

print(nulo_10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Crie um vetor com valores que variam de 10 a 49 (★☆☆)

In [55]:
vetor_aleatorio = np.linspace(10, 50, 10, dtype=int)
print(vetor_aleatorio)

[10 14 18 23 27 32 36 41 45 50]


#### 8. Inverter um vetor (o primeiro elemento torna-se o último) (★☆☆)

In [ ]:
vetor_invertido = np.flip(vetor_aleatorio)

print(vetor_aleatorio, '\n')
print(vetor_invertido)
print(vetor_aleatorio[::-1])

[10 14 18 23 27 32 36 41 45 50]


[50 45 41 36 32 27 23 18 14 10]
[50 45 41 36 32 27 23 18 14 10]


#### 9. Crie uma matriz 3x3 com valores variando de 0 a 8 (★☆☆)

In [ ]:
matriz_3_3 = np.arange(9).reshape(3, 3)

print(matriz_3_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Encontre os índices dos elementos não nulos em [1,2,0,0,4,0] (★☆☆)

In [57]:
q10 = [1,2,0,0,4,0]

print(q10, '\n')
print(np.nonzero(q10))

[1, 2, 0, 0, 4, 0] 

(array([0, 1, 4]),)


#### 11. Crie uma matriz identidade 3x3 (★☆☆)

In [59]:
identidade = np.identity(3)

print(identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Crie um array 3x3x3 com valores aleatórios (★☆☆)

In [ ]:
matriz_3d_aleatoria = np.random.randn(3,3,3) # valores aleatórios da distribuição normal.

print(matriz_3d_aleatoria)

[[[-1.17019819 -0.39187662 -0.49641772]
  [ 1.22307395  0.03445608  0.27793867]
  [ 0.91473891 -1.00503442 -1.7747555 ]]

 [[ 0.74725256 -2.42709308 -0.31824606]
  [ 0.06031084 -1.13844966  1.06969295]
  [-1.03612008 -1.0143991  -0.23823782]]

 [[-1.01720434  2.08687369  1.40816746]
  [-0.41319374  0.81452178  0.20011362]
  [ 0.58085261 -0.08852252  0.94756215]]]


#### 13. Crie um array 10x10 com valores aleatórios e encontre os valores mínimo e máximo (★☆☆)

In [ ]:
matriz_10_10 = np.random.randint(10, 10000, (10, 10)) # Valores aleatórios entre 10 e 10000

print(matriz_10_10, '\n')
print('Mínimo:', matriz_10_10.min())
print('Máximo:', matriz_10_10.max())

[[2200  575 4142 7080 4648 6358 5306 5249 1298 1913]
 [5882 6415 3340 9294 3657 2330 7964 8242 1477 1752]
 [3428 1586 9601 2962 2748 1653 2033 5699 8237 1969]
 [8420 8857  488 4823 5866 6751 3181 7482 6551 4115]
 [9119 5028 8147 8239 8242 8367 6338 4143 2732 3937]
 [8587  354 8753 9375 6150 6077 8331 1899 6131 7275]
 [8021  773 3515 6793 7970 9623 5807 1641  720 8271]
 [5154 1922 3912 5573 7591 7057 2988 8127 4465 2238]
 [9385 5546 9924 8994 2361 2718 2445 7583 2251  679]
 [6368 2016 2063 8603 8879 1933 2239 6758 9572 3378]] 

Mínimo: 354
Máximo: 9924


#### 14. Crie um vetor aleatório de tamanho 30 e encontre o valor médio (★☆☆)

In [ ]:
vetor_aleatorio_30 = np.random.randint(1, 1000, 30) # Valores aleatórios entre 1 e 1000

print(vetor_aleatorio_30, '\n')

print('Média:', vetor_aleatorio_30.mean())

[ 49 258 937 318 892 522 330 533 137 754 125 102 352 500 843 981 333 779
  36 928 630 660 111 943  16 649 800 735 570 584] 

Média: 513.5666666666667


#### 15. Crie uma matriz 2D com 1 na borda e 0 no interior (★☆☆)

In [49]:
def borda_1(linhas, colunas):
    matriz = np.ones((linhas, colunas), dtype=int)
    matriz[1:-1,1:-1] = 0
    return matriz

print(borda_1(4,6),'\n')
print(borda_1(3,3),'\n')
print(borda_1(7,10))

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]] 

[[1 1 1]
 [1 0 1]
 [1 1 1]] 

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


#### 16. Como adicionar uma borda (preenchida com zeros) em torno de um array existente? (★☆☆)

In [ ]:
print(matriz_10_10, '\n')

def borda_0(matriz_ref, c_v=0):
    Z = np.pad(matriz_ref, pad_width=1, mode='constant', constant_values=c_v)
    return Z

print(borda_0(matriz_10_10))

[[2200  575 4142 7080 4648 6358 5306 5249 1298 1913]
 [5882 6415 3340 9294 3657 2330 7964 8242 1477 1752]
 [3428 1586 9601 2962 2748 1653 2033 5699 8237 1969]
 [8420 8857  488 4823 5866 6751 3181 7482 6551 4115]
 [9119 5028 8147 8239 8242 8367 6338 4143 2732 3937]
 [8587  354 8753 9375 6150 6077 8331 1899 6131 7275]
 [8021  773 3515 6793 7970 9623 5807 1641  720 8271]
 [5154 1922 3912 5573 7591 7057 2988 8127 4465 2238]
 [9385 5546 9924 8994 2361 2718 2445 7583 2251  679]
 [6368 2016 2063 8603 8879 1933 2239 6758 9572 3378]] 

[[   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0 2200  575 4142 7080 4648 6358 5306 5249 1298 1913    0]
 [   0 5882 6415 3340 9294 3657 2330 7964 8242 1477 1752    0]
 [   0 3428 1586 9601 2962 2748 1653 2033 5699 8237 1969    0]
 [   0 8420 8857  488 4823 5866 6751 3181 7482 6551 4115    0]
 [   0 9119 5028 8147 8239 8242 8367 6338 4143 2732 3937    0]
 [   0 8587  354 8753 9375 6150 6077 8331 1899 6131 7275    0]
 [   0 8021  773 3515 6793

#### 17. Qual é o resultado da seguinte expressão? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [69]:
print('0 * np.nan:', 'nan')
print('np.nan == np.nan:', 'False')
print('np.inf > np.nan:', 'False')
print('np.nan - np.nan:', 'nan')
print('np.nan in set([np.nan]):', 'True')
print('0.3 == 3 * 0.1:', 'False')

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


#### 18. Crie uma matriz 5x5 com os valores 1, 2, 3 e 4 logo abaixo da diagonal (★☆☆)

In [72]:
triangulo_inf = np.diag(1+np.arange(4),k=-1)

print(triangulo_inf)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Crie um array 8x8 e preencha-a com um padrão de tabuleiro de xadrez (★☆☆)

In [83]:
xadrez = np.ones((8,8), dtype=int)
xadrez[::2, 1::2] = 0
xadrez[1::2,::2] = 0

print(xadrez)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Considere um array de formato (6,7,8), qual é o índice (x,y,z) do 100º elemento? (★☆☆)

#### 21. Crie uma matriz quadriculada 8x8 usando a função `tile` (★☆☆)

#### 22. Normalizar uma matriz aleatória 5x5 (★☆☆)

#### 23. Crie um tipo de dados personalizado (dtype) que descreva uma cor como quatro bytes sem sinal (RGBA) (★☆☆)

#### 24. Multiplicar uma matriz 5x3 por uma matriz 3x2 (produto de matrizes reais) (★☆☆)

#### 25. Dado um array unidimensional, negue todos os elementos que estão entre 3 e 8, no próprio array (★☆☆)

#### 26. Qual é o resultado do seguinte script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Considere um vetor inteiro Z, quais destas expressões são válidas? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. Quais são os resultados das seguintes expressões? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. Como arredondar um array de números de ponto flutuante para um valor diferente de zero? (★☆☆)

#### 30. Como encontrar valores comuns entre duas matrizes? (★☆☆)

#### 31. Como ignorar todos os avisos do NumPy (não recomendado)? (★☆☆)

#### 32. As seguintes expressões são verdadeiras? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. Como obter as datas de ontem, hoje e amanhã? (★☆☆)

#### 34. Como obter todas as datas correspondentes ao mês de março de 2016? (★★☆)

#### 35. Como calcular ((A+B)*(-A/2)) no mesmo local (sem cópia)? (★★☆)

#### 36. Extrair a parte inteira de uma sequência aleatória de números positivos usando 4 métodos diferentes (★★☆)

#### 37. Crie uma matriz 5x5 com valores de linha variando de 0 a 4 (★★☆)

#### 38. Considere uma função geradora que gera 10 números inteiros e use-a para construir um array (★☆☆)

#### 39. Crie um vetor de tamanho 10 com valores variando de 0 a 1, excluindo ambos (★★☆)

#### 40. Crie um vetor aleatório de tamanho 10 e ordene-o (★★☆)

#### 41. Como somar os elementos de um array pequeno mais rapidamente do que com `np.sum`? (★★☆)

#### 42. Considere dois arrays aleatórios A e B e verifique se eles são iguais (★★☆)

#### 43. Tornar um array imutável (somente leitura) (★★☆)

#### 44. Considere uma matriz aleatória 10x2 representando coordenadas cartesianas e converta-a para coordenadas polares (★★☆)

#### 45. Crie um vetor aleatório de tamanho 10 e substitua o valor máximo por 0 (★★☆)

#### 46. Crie uma matriz estruturada com coordenadas `x` e `y` que cubra a área [0,1]x[0,1] (★★☆)

#### 47. Dados dois arrays, X e Y, construa a matriz de Cauchy C (Cij =1/(xi - yj)) (★★☆)

#### 48. Imprima os valores mínimo e máximo representáveis ​​para cada tipo escalar do NumPy (★★☆)

#### 49. Como imprimir todos os valores de um array? (★★☆)

#### 50. Como encontrar o valor mais próximo (de um escalar dado) em um vetor? (★★☆)

#### 51. Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b) (★★☆)

#### 52. Considere um vetor aleatório com formato (100,2) representando coordenadas, encontre as distâncias ponto a ponto (★★☆)

#### 53. Como converter um array de floats (32 bits) em um array de inteiros (32 bits) no mesmo local? (★★☆)

#### 54. Como ler o seguinte arquivo? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. Qual é o equivalente de `enumerate` para arrays NumPy? (★★☆)

#### 56. Gere uma matriz genérica 2D semelhante a uma Gaussiana (★★☆)

#### 57. Como posicionar aleatoriamente p elementos em uma matriz 2D? (★★☆)

#### 58. Subtraia a média de cada linha de uma matriz (★★☆)

#### 59. Como ordenar uma matriz pela enésima coluna? (★★☆)

#### 60. Como determinar se uma determinada matriz bidimensional possui colunas nulas? (★★☆)

#### 61. Encontre o valor mais próximo de um determinado valor em uma matriz (★★☆)

#### 62. Considerando dois arrays com formato (1,3) e (3,1), como calcular a soma deles usando um iterador? (★★☆)

#### 63. Crie uma classe de array que possua um atributo de nome (★★☆)

#### 64. Dado um vetor, como adicionar 1 a cada elemento indexado por um segundo vetor (atenção aos índices repetidos)? (★★★)

#### 65. Como acumular elementos de um vetor (X) em uma matriz (F) com base em uma lista de índices (I)? (★★★)

#### 66. Considerando uma imagem (w,h,3) de (dtype=ubyte), calcule o número de cores únicas (★★☆)

#### 67. Considerando uma matriz de quatro dimensões, como obter a soma dos dois últimos eixos simultaneamente? (★★★)

#### 68. Considerando um vetor unidimensional D, como calcular as médias de subconjuntos de D usando um vetor S de mesmo tamanho que descreve os índices dos subconjuntos? (★★★)

#### 69. Como obter a diagonal de um produto escalar? (★★★)

#### 70. Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)